services:
  postgresql-db:
    container_name: postgresql_db
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
    stop_grace_period: 2m

  telegram-bot:
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    environment:
      - SQL_DB_ENGINE=postgresql
    build:
      dockerfile: Dockerfile
    networks:
      - postgres_network
    depends_on:
      postgresql-db:
        condition: service_healthy
    stop_grace_period: 2m

volumes:
  postgres_data:

networks:
  postgres_network:
